audit_header: false
title: "Wilmington's Best Real Estate Training"
description: Buddy Blake, a top Real Estate Agent in Wilmington, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  # - title: Events
  #   url: #
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/


client:
  name: Buddy Blake
  title:
  license_number:
  about_markdown: |
    RE/MAX Essential and our top-producing ownership team tests and shares the very systems that allow us to be successful, which is why we also specialize in mentoring and helping agents navigate today’s disruptive world of real estate. What makes us different is we believe in transparent leadership. There are no special deals in our office—our agents are on a level playing field, and they’re consistently some of the most profitable agents in the area.  We offer a menu of business plans for every level that you can choose and implement without fear of micromanagement.  We don’t nickel-and-dime agents over services, supplies, and referrals either, and because of our worldwide RE/MAX referral network, our company does not charge extra for referrals—it’s all agent to agent.
  market: Wilmington
  brand: RE/MAX Essential
  brokerage:
  address: 1650 Military Cutoff Rd<br>Wilmington NC 28403
  phone: 910-777-2766
  phone_type:
  phone2:
  phone2_type:
  email: buddyblake@remax.net
  email2: alishamurray@remax.net
  url: http://www.buddyblake.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/BuddyBlakeTeam/
  linkedin_url: https://www.linkedin.com/in/buddyblake
  gplus_url:
  youtube_url:
  twitter_url: https://twitter.com/buddyblake/
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Wilmington Real Estate Podcast with Buddy Blake'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Wilmington Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from RE/MAX Essential - your professional Wilmington Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Wilmington, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Buddy Blake'

images:
  client_headshot_path: /img/headshot.jpg
  client_headshot_path2: /img/headshot2.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Wilmington Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#e11b22'
  theme_color: '#0054a4'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
